# Generated by Django 5.1.6 on 2025-02-13 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_orders'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_name', models.CharField(max_length=20)),
                ('order_email', models.CharField(max_length=20)),
                ('order_phone', models.IntegerField()),
                ('order_City', models.CharField(max_length=30)),
                ('order_state', models.CharField(max_length=30)),
                ('order_zip', models.CharField(max_length=7)),
            ],
        ),
        migrations.DeleteModel(
            name='Orders',
        ),
    ]
