# Generated by Django 5.1.6 on 2025-02-17 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0005_order_delete_orders"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="order_City",
            new_name="order_city",
        ),
    ]
