# Generated by Django 5.1.6 on 2025-02-17 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0006_rename_order_city_order_order_city"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="order_name",
            field=models.CharField(default="", max_length=20),
        ),
    ]
