# Generated by Django 5.1.6 on 2025-02-17 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0007_alter_order_order_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="order_email",
            field=models.CharField(default="", max_length=20),
        ),
    ]
