# Generated by Django 5.1.6 on 2025-02-17 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0008_alter_order_order_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="Offer",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="order",
            name="order_name",
            field=models.CharField(max_length=20),
        ),
    ]
