# Generated by Django 5.1.6 on 2025-02-18 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0009_product_offer_alter_order_order_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="UpdateOrder",
            fields=[
                ("update_id", models.AutoField(primary_key=True, serialize=False)),
                ("order_id", models.IntegerField(default="")),
                ("update_desc", models.CharField(max_length=5000)),
                ("timestamp", models.DateField(auto_now_add=True)),
            ],
        ),
    ]
