# Generated by Django 5.1.6 on 2025-02-20 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0010_updateorder"),
    ]

    operations = [
        migrations.CreateModel(
            name="Buy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("buy_price", models.IntegerField(default=0)),
            ],
        ),
    ]
